#!/usr/bin/env bash

exists () {
    type "$1" &> /dev/null ;
}

CUR_DESKTOP=
if exists /opt/local/bin/chunkc ; then
    CUR_DESKTOP=$(/opt/local/bin/chunkc tiling::query --desktop id)
else
    CUR_DESKTOP="♖"
fi
echo "${CUR_DESKTOP}"

